// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/payments": {
            "post": {
                "description": "Create a payment request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Post payment",
                "parameters": [
                    {
                        "description": "Payment details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PostPaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PostPaymentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/payments/{id}": {
            "get": {
                "description": "get payment by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Get payment by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Payment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GetPaymentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.GetPaymentResponse": {
            "type": "object",
            "required": [
                "amount",
                "card_number_last_four",
                "currency",
                "expiry_month",
                "expiry_year",
                "id",
                "payment_status"
            ],
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "card_number_last_four": {
                    "type": "integer"
                },
                "currency": {
                    "type": "string"
                },
                "expiry_month": {
                    "type": "integer",
                    "maximum": 12,
                    "minimum": 1
                },
                "expiry_year": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "payment_status": {
                    "type": "string",
                    "enum": [
                        "Authorized",
                        "Declined"
                    ]
                }
            }
        },
        "models.PostPaymentRequest": {
            "type": "object",
            "required": [
                "amount",
                "card_number",
                "currency",
                "cvv",
                "expiry_month",
                "expiry_year"
            ],
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "card_number": {
                    "type": "string",
                    "maxLength": 19,
                    "minLength": 14
                },
                "currency": {
                    "type": "string"
                },
                "cvv": {
                    "type": "integer"
                },
                "expiry_month": {
                    "type": "integer",
                    "maximum": 12,
                    "minimum": 1
                },
                "expiry_year": {
                    "type": "integer"
                }
            }
        },
        "models.PostPaymentResponse": {
            "type": "object",
            "required": [
                "amount",
                "card_number_last_four",
                "currency",
                "expiry_month",
                "expiry_year",
                "id",
                "payment_status"
            ],
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "card_number_last_four": {
                    "type": "integer"
                },
                "currency": {
                    "type": "string"
                },
                "expiry_month": {
                    "type": "integer",
                    "maximum": 12,
                    "minimum": 1
                },
                "expiry_year": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "payment_status": {
                    "type": "string",
                    "enum": [
                        "Authorized",
                        "Declined"
                    ]
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "localhost:8090",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Payment Gateway Challenge Go",
	Description:      "Interview challenge for building a Payment Gateway - Go version",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
